export const matchExample = {
  date: "2023-02-07T00:44:32.499Z",
  gameDuration: 2742,
  gameId: 2677343804,
  gameMode: "CLASSIC",
  gameVersion: "13.1.489.3737",
  participants: [
    {
      championId: 58,
      championName: "Renekton",
      participantId: 10,
      spells: ["Flash", "Ignite"],
      spellsIds: [4, 14],
      stats: {
        assists: 5,
        champLevel: 18,
        damageDealtToTurrets: 3910,
        damageSelfMitigated: 44637,
        deaths: 2,
        firstBloodKill: false,
        goldEarned: 17712,
        goldSpent: 17650,
        item0: 3071,
        item1: 3111,
        item2: 6630,
        item3: 3153,
        item4: 3156,
        item5: 6333,
        item6: 3340,
        kills: 5,
        largestKillingSpree: 5,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 2355,
        magicalDamageTaken: 21382,
        physicalDamageDealtToChampions: 18310,
        physicalDamageTaken: 19557,
        totalCs: 285,
        totalDamageDealtToChampions: 22205,
        totalDamageTaken: 42758,
        trueDamageDealtToChampions: 1539,
        visionScore: 48,
        visionWardsBoughtInGame: 2,
        wardsKilled: 4,
        wardsPlaced: 18,
        win: false,
      },
      summonerId: 2874486,
      summonerName: "danieldns",
      teamId: 200,
    },
    {
      championId: 498,
      championName: "Xayah",
      participantId: 9,
      spells: ["Flash", "Heal"],
      spellsIds: [4, 7],
      stats: {
        assists: 4,
        champLevel: 18,
        damageDealtToTurrets: 2071,
        damageSelfMitigated: 16854,
        deaths: 5,
        firstBloodKill: false,
        goldEarned: 18668,
        goldSpent: 18350,
        item0: 3036,
        item1: 6671,
        item2: 3072,
        item3: 3006,
        item4: 3156,
        item5: 6675,
        item6: 3363,
        kills: 10,
        largestKillingSpree: 4,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 768,
        magicalDamageTaken: 11297,
        physicalDamageDealtToChampions: 23178,
        physicalDamageTaken: 10866,
        totalCs: 356,
        totalDamageDealtToChampions: 24129,
        totalDamageTaken: 22865,
        trueDamageDealtToChampions: 182,
        visionScore: 63,
        visionWardsBoughtInGame: 4,
        wardsKilled: 11,
        wardsPlaced: 19,
        win: false,
      },
      summonerId: 1915492,
      summonerName: "Zan",
      teamId: 200,
    },
    {
      championId: 5,
      championName: "XinZhao",
      participantId: 8,
      spells: ["Smite", "Flash"],
      spellsIds: [11, 4],
      stats: {
        assists: 6,
        champLevel: 18,
        damageDealtToTurrets: 548,
        damageSelfMitigated: 44859,
        deaths: 6,
        firstBloodKill: false,
        goldEarned: 15238,
        goldSpent: 13800,
        item0: 1037,
        item1: 6692,
        item2: 1037,
        item3: 3074,
        item4: 3111,
        item5: 3156,
        item6: 3364,
        kills: 3,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 1504,
        magicalDamageTaken: 14164,
        physicalDamageDealtToChampions: 14474,
        physicalDamageTaken: 18791,
        totalCs: 287,
        totalDamageDealtToChampions: 17009,
        totalDamageTaken: 33767,
        trueDamageDealtToChampions: 1030,
        visionScore: 60,
        visionWardsBoughtInGame: 12,
        wardsKilled: 10,
        wardsPlaced: 14,
        win: false,
      },
      summonerId: 4828128,
      summonerName: "lamarzito",
      teamId: 200,
    },
    {
      championId: 131,
      championName: "Diana",
      participantId: 7,
      spells: ["Flash", "Ignite"],
      spellsIds: [4, 14],
      stats: {
        assists: 4,
        champLevel: 18,
        damageDealtToTurrets: 2892,
        damageSelfMitigated: 26566,
        deaths: 7,
        firstBloodKill: false,
        goldEarned: 13580,
        goldSpent: 12185,
        item0: 3157,
        item1: 3135,
        item2: 1011,
        item3: 4636,
        item4: 3047,
        item5: 1052,
        item6: 3340,
        kills: 4,
        largestKillingSpree: 2,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 18826,
        magicalDamageTaken: 20141,
        physicalDamageDealtToChampions: 2098,
        physicalDamageTaken: 10421,
        totalCs: 225,
        totalDamageDealtToChampions: 22497,
        totalDamageTaken: 32397,
        trueDamageDealtToChampions: 1573,
        visionScore: 33,
        visionWardsBoughtInGame: 0,
        wardsKilled: 4,
        wardsPlaced: 17,
        win: false,
      },
      summonerId: 471241,
      summonerName: "Coffler",
      teamId: 200,
    },
    {
      championId: 53,
      championName: "Blitzcrank",
      participantId: 6,
      spells: ["Flash", "Ignite"],
      spellsIds: [4, 14],
      stats: {
        assists: 11,
        champLevel: 16,
        damageDealtToTurrets: 0,
        damageSelfMitigated: 42252,
        deaths: 6,
        firstBloodKill: false,
        goldEarned: 10278,
        goldSpent: 9325,
        item0: 3857,
        item1: 3001,
        item2: 1028,
        item3: 3117,
        item4: 3110,
        item5: 3211,
        item6: 3364,
        kills: 2,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 7126,
        magicalDamageTaken: 15762,
        physicalDamageDealtToChampions: 2844,
        physicalDamageTaken: 12248,
        totalCs: 47,
        totalDamageDealtToChampions: 11338,
        totalDamageTaken: 29051,
        trueDamageDealtToChampions: 1366,
        visionScore: 93,
        visionWardsBoughtInGame: 13,
        wardsKilled: 5,
        wardsPlaced: 44,
        win: false,
      },
      summonerId: 2382668,
      summonerName: "guibode",
      teamId: 200,
    },
    {
      championId: 267,
      championName: "Nami",
      participantId: 5,
      spells: ["Flash", "Exhaust"],
      spellsIds: [4, 3],
      stats: {
        assists: 14,
        champLevel: 16,
        damageDealtToTurrets: 1372,
        damageSelfMitigated: 12434,
        deaths: 5,
        firstBloodKill: false,
        goldEarned: 10276,
        goldSpent: 9075,
        item0: 3853,
        item1: 3107,
        item2: 0,
        item3: 3011,
        item4: 4005,
        item5: 3158,
        item6: 3364,
        kills: 0,
        largestKillingSpree: 0,
        largestMultiKill: 0,
        magicDamageDealtToChampions: 8083,
        magicalDamageTaken: 4102,
        physicalDamageDealtToChampions: 1356,
        physicalDamageTaken: 11654,
        totalCs: 22,
        totalDamageDealtToChampions: 9520,
        totalDamageTaken: 16101,
        trueDamageDealtToChampions: 80,
        visionScore: 120,
        visionWardsBoughtInGame: 7,
        wardsKilled: 13,
        wardsPlaced: 43,
        win: true,
      },
      summonerId: 3625390,
      summonerName: "O Pedro Lyra",
      teamId: 100,
    },
    {
      championId: 236,
      championName: "Lucian",
      participantId: 4,
      spells: ["Flash", "Heal"],
      spellsIds: [4, 7],
      stats: {
        assists: 9,
        champLevel: 18,
        damageDealtToTurrets: 7552,
        damageSelfMitigated: 19548,
        deaths: 6,
        firstBloodKill: false,
        goldEarned: 20171,
        goldSpent: 15100,
        item0: 3036,
        item1: 6671,
        item2: 2420,
        item3: 3031,
        item4: 3094,
        item5: 3006,
        item6: 3363,
        kills: 5,
        largestKillingSpree: 2,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 7346,
        magicalDamageTaken: 7122,
        physicalDamageDealtToChampions: 22473,
        physicalDamageTaken: 17598,
        totalCs: 348,
        totalDamageDealtToChampions: 32436,
        totalDamageTaken: 25326,
        trueDamageDealtToChampions: 2616,
        visionScore: 58,
        visionWardsBoughtInGame: 2,
        wardsKilled: 6,
        wardsPlaced: 17,
        win: true,
      },
      summonerId: 401897,
      summonerName: "Twino3x",
      teamId: 100,
    },
    {
      championId: 82,
      championName: "Mordekaiser",
      participantId: 3,
      spells: ["Flash", "Teleport"],
      spellsIds: [4, 12],
      stats: {
        assists: 5,
        champLevel: 18,
        damageDealtToTurrets: 620,
        damageSelfMitigated: 63145,
        deaths: 6,
        firstBloodKill: false,
        goldEarned: 15959,
        goldSpent: 15800,
        item0: 3075,
        item1: 3047,
        item2: 3116,
        item3: 6665,
        item4: 4637,
        item5: 3068,
        item6: 3340,
        kills: 3,
        largestKillingSpree: 3,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 18596,
        magicalDamageTaken: 3968,
        physicalDamageDealtToChampions: 2429,
        physicalDamageTaken: 25030,
        totalCs: 287,
        totalDamageDealtToChampions: 21235,
        totalDamageTaken: 30818,
        trueDamageDealtToChampions: 209,
        visionScore: 31,
        visionWardsBoughtInGame: 0,
        wardsKilled: 6,
        wardsPlaced: 13,
        win: true,
      },
      summonerId: 3552895,
      summonerName: "Welligton",
      teamId: 100,
    },
    {
      championId: 18,
      championName: "Tristana",
      participantId: 2,
      spells: ["Flash", "Ignite"],
      spellsIds: [4, 14],
      stats: {
        assists: 8,
        champLevel: 18,
        damageDealtToTurrets: 9436,
        damageSelfMitigated: 21540,
        deaths: 7,
        firstBloodKill: true,
        goldEarned: 14704,
        goldSpent: 12960,
        item0: 6672,
        item1: 1038,
        item2: 3156,
        item3: 3026,
        item4: 1053,
        item5: 3006,
        item6: 3363,
        kills: 2,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 2017,
        magicalDamageTaken: 9310,
        physicalDamageDealtToChampions: 8638,
        physicalDamageTaken: 10753,
        totalCs: 241,
        totalDamageDealtToChampions: 12913,
        totalDamageTaken: 21668,
        trueDamageDealtToChampions: 2257,
        visionScore: 33,
        visionWardsBoughtInGame: 0,
        wardsKilled: 6,
        wardsPlaced: 14,
        win: true,
      },
      summonerId: 4750804,
      summonerName: "MiojoAposentado",
      teamId: 100,
    },
    {
      championId: 28,
      championName: "Evelynn",
      participantId: 1,
      spells: ["Smite", "Flash"],
      spellsIds: [11, 4],
      stats: {
        assists: 4,
        champLevel: 18,
        damageDealtToTurrets: 1716,
        damageSelfMitigated: 26570,
        deaths: 0,
        firstBloodKill: false,
        goldEarned: 17748,
        goldSpent: 16000,
        item0: 3041,
        item1: 3152,
        item2: 4645,
        item3: 3020,
        item4: 3135,
        item5: 3089,
        item6: 3340,
        kills: 16,
        largestKillingSpree: 16,
        largestMultiKill: 3,
        magicDamageDealtToChampions: 40279,
        magicalDamageTaken: 10451,
        physicalDamageDealtToChampions: 560,
        physicalDamageTaken: 24738,
        totalCs: 222,
        totalDamageDealtToChampions: 41880,
        totalDamageTaken: 36505,
        trueDamageDealtToChampions: 1040,
        visionScore: 24,
        visionWardsBoughtInGame: 0,
        wardsKilled: 1,
        wardsPlaced: 13,
        win: true,
      },
      summonerId: 16591425,
      summonerName: "Vhex",
      teamId: 100,
    },
  ],
  teams: [
    {
      bans: [
        {
          championId: 22,
          pickTurn: 1,
        },
        {
          championId: 90,
          pickTurn: 3,
        },
        {
          championId: 51,
          pickTurn: 5,
        },
        {
          championId: 26,
          pickTurn: 2,
        },
        {
          championId: 245,
          pickTurn: 4,
        },
      ],
      baronKills: 1,
      dominionVictoryScore: 0,
      dragonKills: 4,
      firstBaron: true,
      firstBlood: true,
      firstDargon: true,
      firstInhibitor: true,
      firstTower: false,
      inhibitorKills: 3,
      riftHeraldKills: 0,
      teamId: 100,
      towerKills: 11,
      vilemawKills: 0,
      win: "Win",
    },
    {
      bans: [
        {
          championId: 412,
          pickTurn: 6,
        },
        {
          championId: 238,
          pickTurn: 1,
        },
        {
          championId: 23,
          pickTurn: 3,
        },
      ],
      baronKills: 1,
      dominionVictoryScore: 0,
      dragonKills: 3,
      firstBaron: false,
      firstBlood: false,
      firstDargon: false,
      firstInhibitor: false,
      firstTower: true,
      inhibitorKills: 0,
      riftHeraldKills: 1,
      teamId: 200,
      towerKills: 5,
      vilemawKills: 0,
      win: "Fail",
    },
  ],
};
