export const matchExample = {
  date: "2023-02-07T03:06:39.937Z",
  gameDuration: 2132,
  gameId: 2677439429,
  gameMode: "CLASSIC",
  gameVersion: "13.1.489.3737",
  participants: [
    {
      championId: 113,
      championName: "Sejuani",
      participantId: 1,
      spells: ["Smite", "Flash"],
      spellsIds: [11, 4],
      stats: {
        assists: 18,
        champLevel: 16,
        damageDealtToTurrets: 1574,
        damageSelfMitigated: 80114,
        deaths: 4,
        firstBloodKill: false,
        goldEarned: 14358,
        goldSpent: 13150,
        item0: 3075,
        item1: 3047,
        item2: 6667,
        item3: 3068,
        item4: 3110,
        item5: 1033,
        item6: 3340,
        kills: 8,
        largestKillingSpree: 3,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 10144,
        magicalDamageTaken: 12213,
        physicalDamageDealtToChampions: 10985,
        physicalDamageTaken: 25134,
        totalCs: 186,
        totalDamageDealtToChampions: 23154,
        totalDamageTaken: 39341,
        trueDamageDealtToChampions: 2024,
        visionScore: 28,
        visionWardsBoughtInGame: 0,
        wardsKilled: 4,
        wardsPlaced: 9,
        win: true,
      },
      summonerId: 16591425,
      summonerName: "Vhex",
      teamId: 100,
    },
    {
      championId: 22,
      championName: "Ashe",
      participantId: 2,
      spells: ["Flash", "Ghost"],
      spellsIds: [4, 6],
      stats: {
        assists: 15,
        champLevel: 16,
        damageDealtToTurrets: 6489,
        damageSelfMitigated: 12085,
        deaths: 3,
        firstBloodKill: false,
        goldEarned: 14547,
        goldSpent: 12650,
        item0: 1055,
        item1: 3086,
        item2: 3036,
        item3: 3006,
        item4: 3153,
        item5: 6673,
        item6: 3363,
        kills: 10,
        largestKillingSpree: 4,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 3704,
        magicalDamageTaken: 7002,
        physicalDamageDealtToChampions: 21816,
        physicalDamageTaken: 11287,
        totalCs: 235,
        totalDamageDealtToChampions: 26375,
        totalDamageTaken: 19435,
        trueDamageDealtToChampions: 854,
        visionScore: 31,
        visionWardsBoughtInGame: 3,
        wardsKilled: 3,
        wardsPlaced: 11,
        win: true,
      },
      summonerId: 1915492,
      summonerName: "Zan",
      teamId: 100,
    },
    {
      championId: 89,
      championName: "Leona",
      participantId: 3,
      spells: ["Ignite", "Flash"],
      spellsIds: [14, 4],
      stats: {
        assists: 19,
        champLevel: 15,
        damageDealtToTurrets: 1053,
        damageSelfMitigated: 43155,
        deaths: 3,
        firstBloodKill: false,
        goldEarned: 9710,
        goldSpent: 8325,
        item0: 3860,
        item1: 2055,
        item2: 3001,
        item3: 3047,
        item4: 3075,
        item5: 3082,
        item6: 3364,
        kills: 4,
        largestKillingSpree: 4,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 6436,
        magicalDamageTaken: 5901,
        physicalDamageDealtToChampions: 2273,
        physicalDamageTaken: 17293,
        totalCs: 44,
        totalDamageDealtToChampions: 10713,
        totalDamageTaken: 24315,
        trueDamageDealtToChampions: 2002,
        visionScore: 88,
        visionWardsBoughtInGame: 7,
        wardsKilled: 9,
        wardsPlaced: 30,
        win: true,
      },
      summonerId: 22664820,
      summonerName: "Galinha Imortal",
      teamId: 100,
    },
    {
      championId: 38,
      championName: "Kassadin",
      participantId: 4,
      spells: ["Flash", "Teleport"],
      spellsIds: [4, 12],
      stats: {
        assists: 16,
        champLevel: 18,
        damageDealtToTurrets: 3525,
        damageSelfMitigated: 27874,
        deaths: 6,
        firstBloodKill: false,
        goldEarned: 13358,
        goldSpent: 12250,
        item0: 3041,
        item1: 6657,
        item2: 3040,
        item3: 3089,
        item4: 3047,
        item5: 0,
        item6: 3363,
        kills: 7,
        largestKillingSpree: 5,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 24845,
        magicalDamageTaken: 8626,
        physicalDamageDealtToChampions: 1772,
        physicalDamageTaken: 21346,
        totalCs: 195,
        totalDamageDealtToChampions: 26964,
        totalDamageTaken: 31831,
        trueDamageDealtToChampions: 346,
        visionScore: 16,
        visionWardsBoughtInGame: 0,
        wardsKilled: 0,
        wardsPlaced: 10,
        win: true,
      },
      summonerId: 4750804,
      summonerName: "MiojoAposentado",
      teamId: 100,
    },
    {
      championId: 58,
      championName: "Renekton",
      participantId: 5,
      spells: ["Flash", "Ignite"],
      spellsIds: [4, 14],
      stats: {
        assists: 9,
        champLevel: 18,
        damageDealtToTurrets: 5283,
        damageSelfMitigated: 29062,
        deaths: 3,
        firstBloodKill: true,
        goldEarned: 16241,
        goldSpent: 14850,
        item0: 3074,
        item1: 3111,
        item2: 6630,
        item3: 3071,
        item4: 3153,
        item5: 0,
        item6: 3340,
        kills: 8,
        largestKillingSpree: 4,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 3503,
        magicalDamageTaken: 12473,
        physicalDamageDealtToChampions: 19055,
        physicalDamageTaken: 23684,
        totalCs: 236,
        totalDamageDealtToChampions: 25353,
        totalDamageTaken: 37741,
        trueDamageDealtToChampions: 2794,
        visionScore: 33,
        visionWardsBoughtInGame: 2,
        wardsKilled: 5,
        wardsPlaced: 13,
        win: true,
      },
      summonerId: 2874486,
      summonerName: "danieldns",
      teamId: 100,
    },
    {
      championId: 111,
      championName: "Nautilus",
      participantId: 6,
      spells: ["Flash", "Exhaust"],
      spellsIds: [4, 3],
      stats: {
        assists: 9,
        champLevel: 13,
        damageDealtToTurrets: 1436,
        damageSelfMitigated: 36848,
        deaths: 9,
        firstBloodKill: false,
        goldEarned: 8635,
        goldSpent: 8400,
        item0: 3860,
        item1: 3190,
        item2: 3117,
        item3: 3075,
        item4: 3024,
        item5: 3067,
        item6: 3364,
        kills: 2,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 7300,
        magicalDamageTaken: 9378,
        physicalDamageDealtToChampions: 1746,
        physicalDamageTaken: 12227,
        totalCs: 41,
        totalDamageDealtToChampions: 9047,
        totalDamageTaken: 22312,
        trueDamageDealtToChampions: 0,
        visionScore: 43,
        visionWardsBoughtInGame: 0,
        wardsKilled: 5,
        wardsPlaced: 19,
        win: false,
      },
      summonerId: 3552895,
      summonerName: "Welligton",
      teamId: 200,
    },
    {
      championId: 141,
      championName: "Kayn",
      participantId: 7,
      spells: ["Flash", "Smite"],
      spellsIds: [4, 11],
      stats: {
        assists: 4,
        champLevel: 14,
        damageDealtToTurrets: 0,
        damageSelfMitigated: 41600,
        deaths: 7,
        firstBloodKill: false,
        goldEarned: 10708,
        goldSpent: 10450,
        item0: 6333,
        item1: 6630,
        item2: 3133,
        item3: 3111,
        item4: 3067,
        item5: 0,
        item6: 3364,
        kills: 4,
        largestKillingSpree: 3,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 0,
        magicalDamageTaken: 14098,
        physicalDamageDealtToChampions: 15922,
        physicalDamageTaken: 26289,
        totalCs: 175,
        totalDamageDealtToChampions: 18494,
        totalDamageTaken: 44131,
        trueDamageDealtToChampions: 2571,
        visionScore: 29,
        visionWardsBoughtInGame: 4,
        wardsKilled: 2,
        wardsPlaced: 9,
        win: false,
      },
      summonerId: 2382668,
      summonerName: "guibode",
      teamId: 200,
    },
    {
      championId: 39,
      championName: "Irelia",
      participantId: 8,
      spells: ["Flash", "Ignite"],
      spellsIds: [4, 14],
      stats: {
        assists: 4,
        champLevel: 17,
        damageDealtToTurrets: 3962,
        damageSelfMitigated: 36198,
        deaths: 8,
        firstBloodKill: false,
        goldEarned: 15436,
        goldSpent: 15150,
        item0: 6665,
        item1: 3111,
        item2: 3153,
        item3: 3091,
        item4: 3074,
        item5: 1029,
        item6: 3364,
        kills: 8,
        largestKillingSpree: 6,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 8598,
        magicalDamageTaken: 9918,
        physicalDamageDealtToChampions: 18316,
        physicalDamageTaken: 20845,
        totalCs: 273,
        totalDamageDealtToChampions: 29607,
        totalDamageTaken: 32810,
        trueDamageDealtToChampions: 2692,
        visionScore: 33,
        visionWardsBoughtInGame: 2,
        wardsKilled: 3,
        wardsPlaced: 12,
        win: false,
      },
      summonerId: 3625390,
      summonerName: "O Pedro Lyra",
      teamId: 200,
    },
    {
      championId: 222,
      championName: "Jinx",
      participantId: 9,
      spells: ["Flash", "Heal"],
      spellsIds: [4, 7],
      stats: {
        assists: 5,
        champLevel: 14,
        damageDealtToTurrets: 1844,
        damageSelfMitigated: 10903,
        deaths: 6,
        firstBloodKill: false,
        goldEarned: 13400,
        goldSpent: 13350,
        item0: 1055,
        item1: 3046,
        item2: 2420,
        item3: 3031,
        item4: 6672,
        item5: 3006,
        item6: 3363,
        kills: 4,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 419,
        magicalDamageTaken: 11017,
        physicalDamageDealtToChampions: 21981,
        physicalDamageTaken: 8860,
        totalCs: 250,
        totalDamageDealtToChampions: 24839,
        totalDamageTaken: 20834,
        trueDamageDealtToChampions: 2438,
        visionScore: 23,
        visionWardsBoughtInGame: 0,
        wardsKilled: 3,
        wardsPlaced: 10,
        win: false,
      },
      summonerId: 401897,
      summonerName: "Twino3x",
      teamId: 200,
    },
    {
      championId: 82,
      championName: "Mordekaiser",
      participantId: 10,
      spells: ["Teleport", "Flash"],
      spellsIds: [12, 4],
      stats: {
        assists: 6,
        champLevel: 16,
        damageDealtToTurrets: 4428,
        damageSelfMitigated: 55808,
        deaths: 7,
        firstBloodKill: false,
        goldEarned: 11471,
        goldSpent: 10550,
        item0: 1054,
        item1: 6665,
        item2: 3047,
        item3: 3116,
        item4: 4637,
        item5: 0,
        item6: 3340,
        kills: 1,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 25305,
        magicalDamageTaken: 9549,
        physicalDamageDealtToChampions: 2447,
        physicalDamageTaken: 20900,
        totalCs: 198,
        totalDamageDealtToChampions: 27752,
        totalDamageTaken: 31670,
        trueDamageDealtToChampions: 0,
        visionScore: 24,
        visionWardsBoughtInGame: 2,
        wardsKilled: 4,
        wardsPlaced: 13,
        win: false,
      },
      summonerId: 659048,
      summonerName: "eu nasci saci",
      teamId: 200,
    },
  ],
  teams: [
    {
      bans: [
        {
          championId: 420,
          pickTurn: 1,
        },
        {
          championId: 136,
          pickTurn: 3,
        },
        {
          championId: 23,
          pickTurn: 5,
        },
        {
          championId: 202,
          pickTurn: 2,
        },
        {
          championId: 145,
          pickTurn: 4,
        },
      ],
      baronKills: 1,
      dominionVictoryScore: 0,
      dragonKills: 3,
      firstBaron: true,
      firstBlood: true,
      firstDargon: true,
      firstInhibitor: true,
      firstTower: false,
      inhibitorKills: 1,
      riftHeraldKills: 1,
      teamId: 100,
      towerKills: 8,
      vilemawKills: 0,
      win: "Win",
    },
    {
      bans: [
        {
          championId: 28,
          pickTurn: 2,
        },
        {
          championId: 54,
          pickTurn: 4,
        },
        {
          championId: 51,
          pickTurn: 6,
        },
        {
          championId: 60,
          pickTurn: 1,
        },
        {
          championId: 254,
          pickTurn: 3,
        },
      ],
      baronKills: 0,
      dominionVictoryScore: 0,
      dragonKills: 1,
      firstBaron: false,
      firstBlood: false,
      firstDargon: false,
      firstInhibitor: false,
      firstTower: true,
      inhibitorKills: 0,
      riftHeraldKills: 1,
      teamId: 200,
      towerKills: 5,
      vilemawKills: 0,
      win: "Fail",
    },
  ],
};
